### PR TITLE
feat: sync llama.cpp

### PR DESCRIPTION
**Pull request by jhen0409**
sync to [0ca416c](https://github.com/ggerganov/llama.cpp/commit/0ca416c91aea4549d9c77e3efeca403e15aa6c75)

### CODE REVIEW

**Comment by jhen0409** [comment]
https://github.com/ggerganov/llama.cpp/pull/10906 seems to break builds on linux arm64 platforms, I need to figure out later.

**Comment by jhen0409** [comment]
Windows ARM64 build is broken: https://github.com/mybigday/llama.node/actions/runs/12441290233/job/34737975818#step:9:1287

@hans00 any ideas?

**Comment by hans00** [comment]
Seems `clang-cl` also not work.
But MinGW chould not work with delayload Node API toolchain.

Maybe need #15 or patch `CMakeFile.txt` to  make it buildable.

**Comment by hans00** [comment]
> patch `CMakeLists.txt`

Looks this change could build.

```diff
---             message(FATAL_ERROR "MSVC is not supported for ARM, use clang")
+++             list(APPEND ARCH_FLAGS /arch:armv8.7)
```

P.S. X Elite is ARMv8.7-A

**Comment by jhen0409** [comment]
> > patch `CMakeLists.txt`
> 
> Looks this change could build.
> 
> ```diff
> ---             message(FATAL_ERROR "MSVC is not supported for ARM, use clang")
> +++             list(APPEND ARCH_FLAGS /arch:armv8.7)
> ```
> 
> P.S. X Elite is ARMv8.7-A

Confirmed it works, but latest commit of llama.cpp still broken on [linux arm64 build](https://github.com/mybigday/llama.node/actions/runs/12553831463). I probably don't have time to deal with that, so I just rollback to https://github.com/ggerganov/llama.cpp/commit/0a11f8b7b5c39fdf6e91ef9674bc68ff08681af7.

**Pull request merged**
